CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_reference VARCHAR(255),
    psp_reference VARCHAR(255),
    amount NUMERIC(20),
    currency VARCHAR(10),
    reference VARCHAR(255),
    payment_method VARCHAR(100),
    status VARCHAR(100),
    auth_code VARCHAR(100),
    failure_message TEXT,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_webhook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    event_code VARCHAR(255),
    success BOOLEAN,
    psp_reference VARCHAR(255),
    event_date TIMESTAMP,
    received_at TIMESTAMP,
    raw_notification TEXT,
    CONSTRAINT fk_payment FOREIGN KEY (payment_id) REFERENCES payment(id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_id ON payment_webhook (payment_id);